language: ruby
sudo: false
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
gemfile:
  - gemfiles/activesupport_3.gemfile
  - gemfiles/activesupport_4.gemfile
  - gemfiles/activesupport_4.2.gemfile
  - gemfiles/activesupport_5.0.gemfile
script: "bundle exec rake spec"
