language: ruby
cache: bundler
sudo: false
rvm:
  - 1.9.3
  - 2.2.0
  - 2.3.1
gemfile:
  - gemfiles/activesupport_3.gemfile
  - gemfiles/activesupport_4.gemfile
  - gemfiles/activesupport_4.2.gemfile
  - gemfiles/activesupport_5.0.gemfile
before_install:
  - gem install bundler
matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/activesupport_5.0.gemfile
    - rvm: 2.2.0
      gemfile: gemfiles/activesupport_5.0.gemfile
script: "bundle exec rake spec"
